### ISSUE TITLE
In-app airplay will not work if shadowrocket is on

### ISSUE THREAD

**Issue by yanyingjie007** [Hsiny/Shadowrocket-Config#1]
any ideas about this?

![img_2793](https://cloud.githubusercontent.com/assets/3379511/22465199/7ef9781c-e7f5-11e6-8cd4-f4a4bed18429.PNG)

![img_2797](https://cloud.githubusercontent.com/assets/3379511/22465204/858926c8-e7f5-11e6-9a5b-4caa11bb3746.PNG)

**Comment by Hsiny** [comment]
是Shadowrocket默认的配置也不行么？如果默认的可以的话，我刚加了几条默认配置里面的规则，你可以测试下AirPlay行不行，我这里没AirPlay设备。如果默认的不行的话，就需要抓一下AirPlay的请求，然后在基本规则里面添加下看是否可行。
