### ISSUE TITLE
请教大神，用url重写屏蔽特定地址广告失败，其他url重写都能生效唯独这条不行

### ISSUE THREAD

**Issue by fhruoefhuof** [Hsiny/Shadowrocket-Config#10]
请教大神我想屏蔽京东金融app的某条启动广告，地址如下
https://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.jpg?width=1242&height=1854

我用shadowrocket的url重写功能写了很多条（如下），但这个地址的图片还是能打开没有被屏蔽，其他app的广告都能用url重写屏蔽，可就是这条广告怎么写都屏蔽不了，请教该怎么写才能屏蔽此广告

^https://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.jpg?width=1242&height=1854 reject

^(http|https)://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.jpg reject

^https://img12.360buyimg.com/jrpmobile/jfs/t11152/221/2398842244/265299/9e9c4da4/5a17838dN98edd21f.jpg reject

^https://img12.360buyimg.com reject 最后哪怕我都这样写url重写了，还是不行啊

PS：此app内容图片和启动广告共用img12.360buyimg.com这个域名，虽然规则能直接屏蔽掉整个域名但不是我所期望的，所以只能用url重写屏蔽此广告

**Comment by fhruoefhuof** [comment]
第一次用github，不知道发在这里合不合适，真是打扰了

**Comment by Hsiny** [comment]
我没试过，不过有些思路你可以试下，

因为很多app广告请求失败后，会用其它域名重试，你可以fillder抓包，阻止上面那条请求，看它会不会再请求别的广告api。

上面链接中 t11152 221 239....这些参数是变化的，最好不要写到规则里，一张图片对应一份参数，我觉得到jfs就好

shadowrocket有个测试规则是否生效的功能，你把url_rewrite规则写好之后，用你抓到的广告url测试下，确定是不是规则写的有问题

你先这样尝试下？有问题再交流

**Comment by fhruoefhuof** [comment]
找到问题了，是https解密里没有添加此域名，添加了就能屏蔽了，谢谢耐心回复

**Comment by Hsiny** [comment]
没事，找到问题就好
