### ISSUE TITLE
添加了配置文件后，应该再怎么使用呀？

### ISSUE THREAD

**Issue by shiyo666666** [Hsiny/Shadowrocket-Config#13]
如题

**Comment by Hsiny** [comment]
你先得装shadowrocket，然后添加配置文件，然后代理模式那里选proxy，就会根据配置文件的规则走了

代理模式选proxy

**Comment by shiyo666666** [comment]
app我装了已经，配置文件也添加了。所以，还需要添加个节点是吧？

**Comment by Hsiny** [comment]
对，需要添加节点才能使用
