### ISSUE TITLE
Facebook.com 被拒绝(rulewithad.txt)

### ISSUE THREAD

**Issue by imnotpopo** [Hsiny/Shadowrocket-Config#3]
在rulewithad.txt中有一条facebook.com,REJECT导致fb上不去，删除后解决

**Comment by Hsiny** [comment]
十分感谢，已经修复了这个问题。原因是```easylist-thirdparty``` 有这样```||facebook.com^*/instream/vast.xml?```的规则，转换时直接截取了^之前的域名，误伤范围太大，刚提交的版本已经过滤了类似的规则
