### ISSUE TITLE
开启配置模式无法连接Telegram

### ISSUE THREAD

**Issue by dechinkey** [Hsiny/Shadowrocket-Config#8]
扫描使用翻墙设置。shadowrocket客户端使用配置模式无法连接Telegram，使用全局代理模式的话可以。因为Telegram客户端后台连接使用的是ip地址而不是域名，规则无法匹配，走的是直接连接导致无法连接

**Comment by Hsiny** [comment]
这个问题目前想到的解决方法就是获取到Telegram的IP段，然后加到baseRule内。我抓包试一下吧。

**Comment by xuzhe1224** [comment]
我也遇到同样的问题

**Comment by Hsiny** [comment]
已经修改了，请更新最新的版本，然后做尝试。
添加了telegram的ip段

**Comment by Hsiny** [comment]
试下最新的能不能连上，然后麻烦反馈下我好做修改。多谢

**Comment by xuzhe1224** [comment]
我试了试，可以了
谢谢！
